### ISSUE TITLE
Planet specific spawn parameters (request)

### ISSUE THREAD

**Issue by DravenXD** [Adam-Norberg/LC_SCP106#10]
I would like to restrict 106's spawning to specific maps, but there aren't any spawning parameters I can set for 106. Not even Lethal Configuration seems to recognize 106 as an enemy. This issue was similar to the one I was having with the Siren Head mod, but that one included planet specific spawning parameters, so I could still configure it even without Lethal Configuration support.
![screencap](https://github.com/Adam-Norberg/LC_SCP106/assets/168028205/52f4e266-9e33-4718-86b6-5d2c24f02449)

**Comment by Adam-Norberg** [comment]
Updated it. I think it's working now, if not let me know and I can try to check out lethal configuration
